module.exports = {
  gci: 'https://codein.withgoogle.com/static/img/og-image.png',
  certifier: 'http://www.iconarchive.com/download/i102616/graphicloads/flat-finance/certificate.ico',
  'blog.jboss-outreach.org': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkEH12RDk12GKeQdd9Ywcn6BKrRPgmagFBFSbShIhymlCo1Jrp4w',
  'facebook-echo-bot': 'http://www.iconninja.com/files/245/45/195/facebook-media-social-like-network-fb-icon.svg',
  'lead-management-android': 'https://github.com/jboss-outreach/lead-management-android/blob/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png?raw=true',
  'cpp-application-code': 'http://maciek.lasyk.info/sysop/wp-content/uploads/2013/12/redhat.png',
  'contact-groups-server': 'http://www.iconarchive.com/download/i85562/graphicloads/100-flat/contact.ico',
  'wiki-explorer': 'https://image.flaticon.com/icons/png/512/49/49360.png',
  'lead-management-server': 'https://github.com/jboss-outreach/lead-management-android/blob/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png?raw=true',
  'compressor-head': 'https://github.com/jboss-outreach/compressor-head-android/blob/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png?raw=true',
  'compressor-head-android': 'https://github.com/jboss-outreach/compressor-head-android/blob/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png?raw=true',
  'rest-android': 'http://maciek.lasyk.info/sysop/wp-content/uploads/2013/12/redhat.png',
  'contact-groups-android': 'http://www.iconarchive.com/download/i85562/graphicloads/100-flat/contact.ico',
  'junit-get-started': 'http://maciek.lasyk.info/sysop/wp-content/uploads/2013/12/redhat.png',
  notes: 'http://maciek.lasyk.info/sysop/wp-content/uploads/2013/12/redhat.png',
  'vertx-gradle-simple': 'http://maciek.lasyk.info/sysop/wp-content/uploads/2013/12/redhat.png',
  'facebook-meme-bot': 'http://www.iconninja.com/files/245/45/195/facebook-media-social-like-network-fb-icon.svg',
  'html-css-js-tasks': 'http://maciek.lasyk.info/sysop/wp-content/uploads/2013/12/redhat.png',
  'compressor-head-web-client': 'https://github.com/jboss-outreach/compressor-head-android/blob/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png?raw=true',
  'rake-tasks': 'http://maciek.lasyk.info/sysop/wp-content/uploads/2013/12/redhat.png',
  'issue-and-pr': 'http://maciek.lasyk.info/sysop/wp-content/uploads/2013/12/redhat.png',
  'cpp-competitive-code': 'http://maciek.lasyk.info/sysop/wp-content/uploads/2013/12/redhat.png',
  'rest-api-vert.x': 'http://maciek.lasyk.info/sysop/wp-content/uploads/2013/12/redhat.png',
  'android-application-code': 'http://maciek.lasyk.info/sysop/wp-content/uploads/2013/12/redhat.png',
};
